### ISSUE TITLE
移动端适配存在问题！

### ISSUE THREAD

**Issue by D-clock** [giscafer/hexo-theme-cafe#11]
作者你好，这是我的站点：http://blog.coderclock.com/ ，在Google搜索后发现提示**您的网页不适合在移动设备上浏览**

![](https://diycode.b0.upaiyun.com/photo/2017/4d5936b73b4ea74bd6512df1f6e46830.png)

我在Android手机上打开后发现确实存在浏览问题

![](https://diycode.b0.upaiyun.com/photo/2017/39ffe41dd229be7dc2f517139419c003.jpg)

**Comment by D-clock** [comment]
补充一下，一直有个提议忘了说，可以把支付宝或微信的付款码放README吗？每次光来提Issue表示很不好意思！

**Comment by giscafer** [comment]
提issue是好事啊。不要客气，改天有空放

**Comment by D-clock** [comment]
坐等，先感谢了。

**Comment by giscafer** [comment]
@D-clock

### 我正常加链接是会自动换行的。如下图。

![hexo-theme-cafe-issues11](https://raw.githubusercontent.com/giscafer/app-study/master/img/hexo-theme-cafe-issues11.png)

markdown为
```

> 多说插件 近期垃圾回复比较多哦。。。元芳们怎么看？？？

> https://github.com/giscafer/hexo-theme-cafe

```

### 这是你的博客效果

以下是更改过样式后的效果（浏览器在线改样式），会自动加滚动条。

![hexo-theme-cafe-issues11-2](https://raw.githubusercontent.com/giscafer/app-study/master/img/hexo-theme-cafe-issues11-2.gif)

建议试试上边`markdown`的方式加是否会自动换行。
或者也可以给一下你的markdown代码看看。

二维码已放，谢谢老板打赏

_最新代码已经修改样式_

**Comment by D-clock** [comment]
好滴，晚上回家试试。

**Comment by D-clock** [comment]
试了好像还是有问题，我的markdown编写如下：

```

> https://github.com/Curzibn/Luban

Luban，也称鲁班。该库作者一针见血的提出当前图片压缩处理的一些问题：**单纯对图片进行裁切，压缩已经有很多文章介绍。但是裁切成多少，压缩成多少却很难控制好，裁切过头图片太小，质量压缩过头则显示效果太差**。所以，他通过微信朋友圈发送近100张不同分辨率图片，对比原图与微信压缩后的图片逆向推算出来的压缩算法，具体的算法实现在项目中有详细说明介绍。使用上，支持普通调用方式外，也支持RxJava！

```

**Comment by D-clock** [comment]
@giscafer 哈，是我粗心了，合并你的代码后，没有问题了，谢谢作者耐心解答。
