### ISSUE TITLE
详情页可以增加文章推荐么？或者说热评

### ISSUE THREAD

**Issue by jin10086** [giscafer/hexo-theme-cafe#12]

**Comment by jin10086** [comment]
感觉详情页比较单调

**Comment by giscafer** [comment]
就是为了简洁才只给个目录。如果详情页给其他widget，需要把目录的方式换掉，不是目前默认的悬浮效果，因为这样会遮挡其他东西。

顺便说，目录现在支持两者方式展示。

- 热评目前没发现网易跟帖可以支持

**Comment by jin10086** [comment]
好的,谢谢
