### ISSUE TITLE
报个issue，微信的二维码图片没有做大小限制。

### ISSUE THREAD

**Issue by jeffreys-cat** [giscafer/hexo-theme-cafe#13]
如下图所示。

![image](https://cloud.githubusercontent.com/assets/11832969/26668625/309a23e6-46dd-11e7-9d39-ebe65d8e876b.png)

**Comment by jeffreys-cat** [comment]
将图片换成258*258,但是会有些不清楚耶

**Comment by giscafer** [comment]
fixed at https://github.com/giscafer/hexo-theme-cafe/commit/87659f41ce44a29ffcf69d14cebb71a50340bad4
