### ISSUE TITLE
博客大标题看着有些别扭

### ISSUE THREAD

**Issue by Svtter** [giscafer/hexo-theme-cafe#14]
![image](https://cloud.githubusercontent.com/assets/5856931/26670400/1095e5e2-46e4-11e7-82be-171d68145946.png)

如图所示，文章标题比博客名称大的有点多，感觉有些违和，不如修改一下？

**Comment by giscafer** [comment]
@Svtter 不过我个人觉得1.6em很合适呀。。

**Comment by Svtter** [comment]
参考的阮大的博客是1.8em…这种东西仁者见仁智者见智，我自己改一下好了
