### ISSUE TITLE
请问关于页应该怎么生成？

### ISSUE THREAD

**Issue by pmtea** [giscafer/hexo-theme-cafe#16]
谢谢giscafer的主题，很喜欢，问题RT

**Comment by ZQiang94** [comment]
- 创建一个about文件夹在source中，并在里面创建index.md,用于展示about页面,，如下两图

![image](https://cloud.githubusercontent.com/assets/7663942/26779643/c327f1b4-4a18-11e7-9cd2-b87eb7229267.png)
![image](https://cloud.githubusercontent.com/assets/7663942/26779657/d1f97f82-4a18-11e7-9347-9d37038557f6.png)

- 修改配置文件，如下两图

![image](https://cloud.githubusercontent.com/assets/7663942/26779712/151f049e-4a19-11e7-91f4-a4858e14654a.png)
![image](https://cloud.githubusercontent.com/assets/7663942/26779695/010cf90c-4a19-11e7-86e3-1f93c1a78c61.png)

**Comment by giscafer** [comment]
@ZQiang94 正解，很详细
