### ISSUE TITLE
评论系统能支持畅言吗？

### ISSUE THREAD

**Issue by D-clock** [giscafer/hexo-theme-cafe#17]
Hi，giscafer，晚上好。用了一段时间云跟帖后，实在无法忍受体验了。能够支持畅言作为评论系统么？

> http://changyan.kuaizhan.com/

**Comment by giscafer** [comment]
网易跟帖我也觉得不好用。这几天有空会加一下。

**Comment by giscafer** [comment]
Add changyan comments commit at  https://github.com/giscafer/hexo-theme-cafe/commit/c25a3af5c30ebba8704c44bf92f893ea8c5f8bbd

**Comment by giscafer** [comment]
畅言评论插件，要求网站域名需要备案。
http://blog.giscafer.com/2017/06/07/hexo-changyan/

**Comment by D-clock** [comment]
我的站点换了畅言后，移动端评论框出不来！ http://blog.coderclock.com/  

![](https://diycode.b0.upaiyun.com/photo/2017/12032b1b7397e249b50e0b267d377db7.png)

**Comment by giscafer** [comment]
@D-clock
浏览器模拟手机移动端是可以出现的。手机访问确实不可以。这个需要找原因。
![changyan](https://user-images.githubusercontent.com/8676711/26872547-7af30d92-4ba9-11e7-8e0e-6f3e0b08460e.png)

**Comment by D-clock** [comment]
好滴，这个站点用畅言，在移动端就能打开，http://droidyue.com/

**Comment by giscafer** [comment]
@D-clock 再试试。可能代码格式化问题影响，调整了一下。目前公司没有hexo环境，还没测试。代码是官方给的，应该不会有问题。

**Comment by D-clock** [comment]
ok了，已经可以正常显示，thx！
