### ISSUE TITLE
你好，这主题非常好，现提几个建议

### ISSUE THREAD

**Issue by jerry011235** [giscafer/hexo-theme-cafe#2]
你好，这主题非常好，现提几个建议：
1.建议集成`hexo-generator-search`插件，然后让搜索框变长点，关键字高亮。参考[http://forsigner.com/search/](http://forsigner.com/search/)的样子。
[http://moxfive.xyz/2016/05/31/hexo-local-search/](http://moxfive.xyz/2016/05/31/hexo-local-search/)
2.仿造landscape-plus，顶部增加几个社交按钮，比如知乎，github等。
3.下载了最新0.5.1版，还是没有返回顶部按钮。
4.sidebar: right 改为 bottom ，其他没动，会报错。

**Comment by giscafer** [comment]
@jerry011235 感谢建议，一些建议会参考，日后时间修改升级会作为取舍依据，改动会在release版本有说明。
- 第三点，返回顶部功能添加后没有发布版本。现在发布了，下载`0.5.2`版本即可有，[演示站点](http://cafe.giscafer.com/)是最新效果，只有长的文章内容页才会显示

**Comment by giscafer** [comment]
已修改全站显示回到顶部按钮

**Comment by jerry011235** [comment]
好的，感谢！
另外听说新的社会化评论[来必力](https://livere.com/)不错，能否集成？

**Comment by giscafer** [comment]
已安装来必力的网站
23,916 个
 
**累计用户数**
24,374,872 名
 
顾客司
1,107 个
 
**累计评论数**
25,658,693 个

用户数和评论数如此接近，表示不够火。第一次听，看过很多博客，没见过集成这个的，评论插件满足评论要求即可，不是越多越好。

**Comment by jerry011235** [comment]
没事，主要是觉得Disqus被墙了，多说一直没有盈利，倒闭是迟早的事，国内没几个好用的第三方评论系统了。只能看下畅言和网易云跟帖的发展了。

**Comment by giscafer** [comment]
嗯，`Disqus`在国内不行。国内博客大部分都用多说。或者是通过邮件回复的那种方式。

**Comment by jerry011235** [comment]
对了，归档页面的日期格式能否调整成例如03-13的样式，目的是排列整齐，参考[http://forsigner.com/archives/](http://forsigner.com/archives/)，目前[http://giscafer.com/archives/](http://giscafer.com/archives/)不是太整齐。

**Comment by giscafer** [comment]
已修改。http://cafe.giscafer.com/archives/

**Comment by frmachao** [comment]
你好
 右面的文章目录能否添加滚动条，因为在文章目录过长的时候 右侧目录显示不全

**Comment by giscafer** [comment]
@frmachao 已经[fixed bug ](https://github.com/giscafer/hexo-theme-cafe/commit/16fd2b7bd6845d05aab455a3d94f40e658869b3f)

进入主题更目录：`git pull` 更新最新代码即可。

**Comment by levinit** [comment]
我也提点建议：
增加一个总标签页 列出所有标签
增加一个总分类目录页面 列出所有目录
标签和目录都是在首页才能找到 不太方便 加上在文章最后标签色浅而字体小 比较费神

---
我看了下hexo文档 原来文章中的tags和catigories不适用于分页。看来我提的建议可以略过了 ：D

**Comment by giscafer** [comment]
@levinit
1、文章最后标签故意灰色不突出。标签widget除了标签云，还有标签，可以切换看一下效果。
2、标签和目录都是在首页才能找到 ，这个是刻意做的。文章预览的时候，有目录的情况下只显示目录，没目录显示最新文章；显示其他东西太多，不简洁；而主题宗旨是简洁，所以文章详情不会显示目录和标签，这是**cafe**主题设计如此。
3、建议的总标签页可能会考虑，总分类目前看情况。

主题的一些小众问题的样式，如果会写CSS，可以自己做调整。目录位置[cafe/source/css/custom.styl](https://github.com/giscafer/hexo-theme-cafe/blob/master/source/css/_partial/custom.styl)，此处写的样式会覆盖全局的。

类似这些小问题，不会针对每个人提议都会去修改，这好比产品设计，某个用户提议怎么改，不能立马去改，也要看总体用户的使用习惯和观点，以及原本的设计理念。

总之，感谢建议。

**Comment by levinit** [comment]
小的方面 自己修改
建议这些 你根据主题既定理念选择性采纳就好 :）

**Comment by jerry011235** [comment]
你好，发现一些其他的主题都有集成本地搜索（用`hexo-generator-search`插件），就类`Landscape`主题没有，所以强烈建议你能集成下，毕竟默认的google搜索在国内不好用。
https://github.com/PaicHyperionDev/hexo-generator-search
http://wzpan.github.io/hexo-theme-freemind/404.html
http://moxfive.xyz/2016/05/31/hexo-local-search/

**Comment by giscafer** [comment]
@jerry011235 之前是觉得Hexo博客一般都是程序猿使用的，作为程序猿，翻墙是基本功，google站外搜索也很不错。
我看吧，再考虑一下要不要集成。

**Comment by giscafer** [comment]
@jerry011235 @levinit 评论系统已更换为网易云跟帖，并支持原来多说评论系统数据的导入。
cafe主题发布v1.0版本，感谢支持。
