### ISSUE TITLE
Cafe主题造成hexo s命令不起作用问题

### ISSUE THREAD

**Issue by giscafer** [giscafer/hexo-theme-cafe#23]
由于为了实现动态生成随机文章，新增了文件。
`themes\cafe\scripts\extend.generator.js`，里边方法：
```javascript
extend.generator.register('random_post',function (locals, render, callback) {

//……

}
```
造成`hexo s`命令失效，目前原因未知。可能是和hexo版本有问题，`hexo g`和`hexo d`命令并不受影响。

如果不想生成随机推荐文章，就注释上边方法或者删除该文件即可。那样`hexo s`命令即可恢复正常

找到解决方案后会关闭此ISSUE

**Comment by D-clock** [comment]
执行hexo s命令后窗口会一直不断滚动输出信息，是正常的么？

**Comment by giscafer** [comment]
@D-clock 已删除输出日记。

**Comment by D-clock** [comment]
@giscafer 刚刚同步了一下，发现还是有日志不断输出，我用的命令是hexo s -p 端口号

**Comment by giscafer** [comment]
@D-clock 试了没发现有日记啊。提供一下日记信息

**Comment by D-clock** [comment]
![](https://diycode.b0.upaiyun.com/photo/2017/3a89d4dd4978fe28c2897e56270407eb.png)

这是我的控制台log，不断的输出10个url文章链接，以前只会输出一次，这些url是提交给百度的。

**Comment by giscafer** [comment]
这个是你装的百度什么插件输出的日记吧，不是主题的日记。

**Comment by D-clock** [comment]
@giscafer 对的，但是之前这个插件只会输出一次log，我这边也再仔细看看吧，谢谢你的解答。
