### ISSUE TITLE
大大...死活不能代码块语法高亮啊

### ISSUE THREAD

**Issue by nanqinlang** [giscafer/hexo-theme-cafe#25]
站点的config.yml当然已经是设置了highlight的三个true true true了  
就是比如图上这样 我用了\```和 \```bash 和\```shell 这三种  
都有代码块 但是都是图上这样 不会变色 一点变色都没有  
甚至我去试了写java/js/css和对应代码 都还是不变色  
![qq](https://user-images.githubusercontent.com/26526543/28779563-3174eb10-7636-11e7-926b-7884dd57913d.png)

**Comment by giscafer** [comment]
http://blog.giscafer.com/2017/07/04/ionic-imagepicker/
http://blog.giscafer.com/2017/07/05/ionic-custom-component/
我的有啊。

cafe主题代码样式颜色相对浅色。

**Comment by nanqinlang** [comment]
@giscafer  
但是我也没改过什么啊 就是只设置了下两个config.yml  
我还得继续去试试

**Comment by nanqinlang** [comment]
看了代码发现highlight被吞了...这个要怎么搞
![qq](https://user-images.githubusercontent.com/26526543/28782644-5719f432-7640-11e7-8178-1b4f8e192525.png)

**Comment by giscafer** [comment]
不要用shell，试试其他xml等可以高亮吗。shell本人也不清楚

**Comment by nanqinlang** [comment]
@giscafer  
我来汇报结果了 实测结果是 shell也能变色 只是变色的部分好少 完全不能和例如github或者编辑器比
