### ISSUE TITLE
希望可以调整首页位置 比如将about页面设为首页

### ISSUE THREAD

**Issue by leetcola** [giscafer/hexo-theme-cafe#27]
另外 
about页面的内容如何添加？

**Comment by giscafer** [comment]
about页面：https://github.com/giscafer/hexo-theme-cafe/issues/16

不可能将about作为首页的。如果需要，自己修改。

或者自己写个首页就行了。如 http://giscafer.com

**Comment by leetcola** [comment]
多谢解答！
