### ISSUE TITLE
公式无法渲染

### ISSUE THREAD

**Issue by leetcola** [giscafer/hexo-theme-cafe#28]
rt，编辑的latex公式无法正常显示，http://cafe.giscafer.com/2017/04/15/mathjax-test/#more 展示页面公式也显示不出来

**Comment by giscafer** [comment]
@chong-w 网速问题吧，我这里是好的。公式渲染需要下载个mathjax.js，这个是国外的cdn。

![qq 20170826164253](https://user-images.githubusercontent.com/8676711/29739941-a30b31a2-8a7d-11e7-9806-8812d742899f.png)

**Comment by leetcola** [comment]
好像是网速原因，刚刚死活打不开，现在好了…thx
但是手机上网页还是显示不出，是不是可以把配置文件里mathjax的地址换成国内的镜像提高加载速度？

**Comment by leetcola** [comment]
目前地址换成了 https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML 应该是官方的最新版本 速度貌似有所提升 手机能看了
