### ISSUE TITLE
如何在主页上加一段自我介绍呢？

### ISSUE THREAD

**Issue by leetcola** [giscafer/hexo-theme-cafe#29]
如链接所示：https://probberechts.github.io/cactus-dark/
仓库在：https://github.com/probberechts/cactus-dark

**Comment by giscafer** [comment]
首页自己扩展，不会加到博客主题中。

例如 
home:  http://giscafer.com
blog : http://blog.giscafer.com

**Comment by leetcola** [comment]
好的
