### ISSUE TITLE
报错 真的不知道我做了什么啊

### ISSUE THREAD

**Issue by nanqinlang** [giscafer/hexo-theme-cafe#32]
已经各种重装了还是这样
![fatal](https://user-images.githubusercontent.com/26526543/31912322-0cac55b6-b876-11e7-88f4-7bd7ba1b8fc2.png)

**Comment by giscafer** [comment]
这个到hexo找解决方案https://github.com/hexojs/hexo ， 环境问题吧

**Comment by nanqinlang** [comment]
因为已经用了好久了，却突然变成这样。。。我什么都没动过，特别懵

**Comment by giscafer** [comment]
@nanqinlang 重装一下环境和其他版本吧，这个问题好像见到过，建议到hexo issue找一下解决方案

**Comment by nanqinlang** [comment]
现在变成了这样。。。
![fatal](https://user-images.githubusercontent.com/26526543/31954937-7c1734d6-b919-11e7-8787-a1d3880a5bca.png)

**Comment by giscafer** [comment]
依赖没下好吧。不能识别ejs语法？

**Comment by nanqinlang** [comment]
hexo-render-ejs 已经npm install --save 过了。  
我是本来稳定用了两个月了，然后突然就成这样了，试过反复换了系统平台、换了 git/node 版本，hexo 也重装好多了遍。。

**Comment by giscafer** [comment]
@nanqinlang 你确定换成其他主题可以？ 比如试试；https://github.com/hexojs/hexo-theme-landscape

**Comment by nanqinlang** [comment]
换主题我发现了两种情况：  
1. 全新安装 hexo 后，第一次就用 `cafe` 主题 generate 的话，就会图上 `unhandled rejection typeerror` 报错，之后换用其它主题都会同样报错
2. 全新安装 hexo 后，第一次使用 `landscape` 默认主题生成页面成功，没报错。但换到 `cafe` 后又发生了第一种情况，如果不重装 hexo，怎么换主题都会 error
