### ISSUE TITLE
首页文章预览

### ISSUE THREAD

**Issue by DiversKing** [giscafer/hexo-theme-cafe#33]
现在是默认全部显示啊.  望添加可以预览的的配置选项. 
在使用另一个主题: NexT时, 有如下配置.
# 首页预览
auto_excerpt: 
    enable: true
    length: 150

**Comment by giscafer** [comment]
文章加 `<!--more-->` 是截取摘要部分

**Comment by DiversKing** [comment]
ok. 谢谢. 按您说的方式可以做到.
