### ISSUE TITLE
标题栏固定问题？

### ISSUE THREAD

**Issue by ghost** [giscafer/hexo-theme-cafe#35]
请问最上面的“首页 归档 这一栏能一直固定在顶部吗？”

**Comment by giscafer** [comment]
@liangzi-xuan  可以自己改样式，覆盖就行了。

自定义样式可以在[`custom.styl`](https://github.com/giscafer/hexo-theme-cafe/blob/master/source/css/_partial/custom.styl)下写，会覆盖全局
