### ISSUE TITLE
 “关于”页面里面添加内容

### ISSUE THREAD

**Issue by ghost** [giscafer/hexo-theme-cafe#36]
请问这个主题的 “关于”页面里面内容怎么添加自己的呢 谢谢

**Comment by giscafer** [comment]
建议养成习惯：先搜索issues里是否有人提问过。

问题可以搜索找到：https://github.com/giscafer/hexo-theme-cafe/issues?q=is%3Aissue+is%3Aclosed+label%3Aquestion
