### ISSUE TITLE
不支持TOC和自动截断显示吗

### ISSUE THREAD

**Issue by levinit** [giscafer/hexo-theme-cafe#4]
请问这个主题是不是不能显示markdown的toc
以及能否添加一个自动截断显示功能，首页展示不要将文章全文显示出来，md手动加more不太适应：D
另外标签云上的字体也好小呀

**Comment by giscafer** [comment]
这个<！--more-->是要改hexo框架源码了。不是主题的功能。不应该主题加的。

**Comment by levinit** [comment]
toc是支持的，我刚看错了。

**Comment by giscafer** [comment]
云标签字体调整了。效果见：http://giscafer.com

**Comment by levinit** [comment]
更新了，看到了。多谢：D
