### ISSUE TITLE
怎么做到点击另外的分类不会覆盖前面一个窗口？

### ISSUE THREAD

**Issue by xiaomizhou66** [giscafer/hexo-theme-cafe#40]
就是类似 target-black 的功能？比如说希望点击另外一个分类的文章之后，不要覆盖正在看的文章，
就是希望两个文章同时看的，，，，却被覆盖掉了，很难回来

**Comment by giscafer** [comment]
博客主题修改 `thems/cafe/layout/_partial/post/title.ejs` 文件，如下代码a标签，加入 `target="_blank"`即可

https://github.com/giscafer/hexo-theme-cafe/blob/3e275b5c3436eb7f434978a36d29b4beb79f9037/layout/_partial/post/title.ejs#L3


阅读更多则修改文件：

https://github.com/giscafer/hexo-theme-cafe/blob/3e275b5c3436eb7f434978a36d29b4beb79f9037/layout/_partial/article.ejs#L18
