### ISSUE TITLE
使用教程说明太简单了

### ISSUE THREAD

**Issue by silaoA** [giscafer/hexo-theme-cafe#45]
感谢作者，很喜欢这个theme，但仍有以下疑问，希望能有更详细的教程。
如何组织文件夹、markdown文件以适应标签分类？
markdown的引用，生成html后字体很大，比一级标题都大，如何解决？
首页widget的名称，除了social widget有social_title设置项，可以设置名称外，其他都是英文，但是作者你的博客 http://blog.giscafer.com 中是中文，设置项在哪里？

**Comment by giscafer** [comment]
@silaoA 建议了解一下hexo博客的配置文件，和主题的配置文件说明。熟悉hexo的话，别的主题不需要介绍都是可以直接拿来用的。另外，本主题是基于官方主题修改的[hexo-theme-landscape](https://github.com/hexojs/hexo-theme-landscape)，所以，官方的文档建议先看吧，或者找资料，主题都一样的设置方式，最好先理解。避免有问题不知道哪里调整。
