### ISSUE TITLE
文章目录自动添加序号与图片自动添加底部标题

### ISSUE THREAD

**Issue by ZhuJiaYou** [giscafer/hexo-theme-cafe#46]
@giscafer ，你好：

有两个问题。
1. 文章目录总是会自动添加序号，不知道能否关闭这一功能？
因为有自动编号，自己在文章中加编号就不方便了；如果文章中没有标题序号，阅读起来也不是很方便。
![menu](https://user-images.githubusercontent.com/32535222/57966993-d277ea80-798b-11e9-8754-d76ef3a6b3d9.JPG)

2. 文章中插入图片，图片下总是显示图片名称，不知道能否关闭？
有些图片有图片名可能会利于阅读，但是有些则不需要。
![pics_problem](https://user-images.githubusercontent.com/32535222/57967010-11a63b80-798c-11e9-8ba3-5bd1b7df2ecb.JPG)

**Comment by giscafer** [comment]
https://github.com/giscafer/hexo-theme-cafe/blob/3e275b5c3436eb7f434978a36d29b4beb79f9037/layout/_widget/post_content.ejs

可以去看一下hexo api，自己调整这里，这里就是目录生成的地方

**Comment by ZhuJiaYou** [comment]
1. 经验证，对于第一个问题，修改 themes/cafe/layout/_widget/post_content.ejs 文件第10行，toc中加入{list_number: false}参数，即不自动生成目录序号。
```ejs
<%- toc(postObj.content || 'giscafer') %>
```
改为：
```ejs
<%- toc(postObj.content || 'giscafer', {list_number: false}) %>
```
即可。

2. **不知第二个问题有没有解？**

**Comment by giscafer** [comment]
@ZhuJiaYou 第二个问题需要修改组件了。主题用的是fancybox预览大图，但是真正解析是markdown解析生成html的，hexo自带的吧。这个只要自己写图片代码时，不加title就行了，不需要纠结啊，比如 

有title的
```markdown
![图片标题](图片链接)
```

无title的：
```markdown
![](图片链接)
```

**Comment by ZhuJiaYou** [comment]
@giscafer ，嗯，确实，这也是一种解法。
多谢指点！😀
