### ISSUE TITLE
DEMO页源代码

### ISSUE THREAD

**Issue by wayson** [giscafer/hexo-theme-cafe#6]
你好，这个主题相当不错。可是我还是一个hexo新手，请问可以提供一下这个demo页http://cafe.giscafer.com/ 的源代码吗？谢谢。

**Comment by giscafer** [comment]
demo代码就在本工程的分支[blog-demo-src](https://github.com/giscafer/hexo-theme-cafe/tree/blog-demo-src)

**Comment by wayson** [comment]
看到了，谢谢啊。
