### ISSUE TITLE
多说评论即将关闭，请问可否支持集成其他第三方评论系统呢？

### ISSUE THREAD

**Issue by D-clock** [giscafer/hexo-theme-cafe#7]
> http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241

**Comment by giscafer** [comment]
@D-clock 恩，会换的，待考虑选择其他评论系统。
有好的可以建议。

**Comment by D-clock** [comment]
@giscafer 感谢作者，回复好及时。目前国内觉得不错的有网易云跟帖、畅言、友言等几个。

**Comment by giscafer** [comment]
@D-clock 恩，好的，我有时间会对比一下优势，另外还得考虑是否支持多说评论导入。

**Comment by giscafer** [comment]
@D-clock  网易云跟帖已添加 https://github.com/giscafer/hexo-theme-cafe/commit/ef00700fdcee3a14a7d2e25b746a02b3683bf493

使用方式：http://cafe.giscafer.com/2017/04/14/gentie-test/
