### ISSUE TITLE
文章首页不显示字段

### ISSUE THREAD

**Issue by wangzhezhe** [giscafer/hexo-theme-cafe#8]
请问是否有控制文章在首页是否显示的字段，如果需要添加对应的字段，添加对应的判断逻辑应该在哪个文件中进行修改，谢谢。

**Comment by giscafer** [comment]
这个你找一下landscape的主题看一下是否支持，本主题是基于其基础二次开发的。另外，这可能是hexo自带的功能，你看网上搜索hexo相关的修改支持吗，如果有不支持反馈一下，下个版本会添加。

**Comment by wangzhezhe** [comment]
之前找了一下，大概意思就是在提交文章的时候添加一个控制字段，然后在把render的部分包装一下，比如可以参考[这个](http://www.xbool.com/article-not-show-home/) 以及[这个](http://forwardkth.github.io/2016/05/08/next-theme-post-visibility/)，但是我不太熟悉hexo的相关实现文件，这个主题不太确定应该在哪个地方改。@giscafer

**Comment by wangzhezhe** [comment]
对于ejs的相关语法不是太熟悉，就在_partial/archive.ejs中加了简单的判断
```
  <% if (post.visible){ %>
    <%- partial('article', {post: post, index: true}) %>
  <% } %>
```
我本来想设置成默认的时候是显示，加了某个参数的时候是不显示，但是不知道这里具体应该怎么写也没弄好，就临时先这样弄了（加了参数时候显示不加参数的时候不显示）。

**Comment by giscafer** [comment]
@wangzhezhe  改成这样
```
  <% if ( post.visible!==false){ %>
    <%- partial('article', {post: post, index: true}) %>
  <% } %>
```

除非文章加`visible:false`，不然都会默认显示

**Comment by wangzhezhe** [comment]
谢谢帮助！@giscafer
