### ISSUE TITLE
是否可以增加友链功能？

### ISSUE THREAD

**Issue by D-clock** [giscafer/hexo-theme-cafe#9]
作者你好，这个主题能够增加友链功能吗？

**Comment by giscafer** [comment]
@D-clock 目前没提供，下个版本添加。

**Comment by giscafer** [comment]
@D-clock 友链功能已添加https://github.com/giscafer/hexo-theme-cafe/commit/ef809e77cf4846d4ed8b86c3b72b4dc3f669857d

但未发布新版本，`git clone`最新源码使用即可。

**Comment by D-clock** [comment]
棒，感谢！
